### ISSUE TITLE
Scaling, instead of margin size change

### ISSUE THREAD

**Issue by pcholt** [efortuna/coverflow#2]
I'm trying a first contribution to a flutter library, so be kind. 
Attempting to get the cards to scale with matrix BUT I can't get the size of the element.

              var transformation = (result < index)
              ? new Matrix4.compose(
                  new Vector3(
                      .0, -value1 * scaleMultiplier * context.size.height / 2, 0.0),
                  new Quaternion.identity(),
                  new Vector3.all(value))
              : new Matrix4.compose(
                  new Vector3(value1 * scaleMultiplier * context.size.width / 2,
                      value1 * scaleMultiplier * context.size.width  / 2, 0.0),
                  new Quaternion.identity(),
                  new Vector3.all(value));

I'll keep working on it, but it seems when an AnimatedBuilder.builder is called there is no context size available.  Any advice?

**Comment by efortuna** [comment]
Hi @pcholt sorry for my delay in responding. Thanks for your interest and the question! As you alluded to in your question, you can't get the size of an element during it's build phase because it hasn't been built yet! The same goes for other elements -- you don't have that info until the layout phase (re- builders have been called) is done. 

Depending on what you're trying to do, you have a couple of options. Check out this link: https://github.com/flutter/flutter/wiki/Creating-Responsive-Apps
I think what you might be able to use is the screen size with MediaQuery.of.
Otherwise try using a LayoutBuilder to get size constraints and decide how to scale items from there.

I hope this helps!
